verison: "3.8"
name: docker-node-app-runner

services:
  docker-node-app-runner":
    image: barbarbar338/docker-node-app-runner:buildx-latest
    container_name: docker-node-app-runner
    restart: unless-stopped
    environment:
      # These environment variables are required.
      - runner__GIT_USERNAME=
      - runner__PERSONAL_ACCESS_TOKEN=
      - runner__GIT_FQDN=
      - runner__GIT_REPO_NAME=
      - runner__GIT_REPO_OWNER=
      - runner__GIT_SERVER_SECURE=
      # If your app depends on extra dependencies then add them here
      - runner__EXTRA_ALPINE_DEPENDENCIES=
      # And your normal environment variables goes here
      - PORT=3000
      - NODE_ENV=production
      # ...
    # If you want you can map repo_temp volume too
    # volumes:
      # - ./repo_files:/app/repo_temp
